title: Cronologia da Ciência
description: Uma linha do tempo interativa contando um pouco da história da ciência
baseurl: "/cronologia-da-ciencia"
url: "https://felipeipe.github.io"

exclude:
  - /.vscode/

collections:
  - events
